# Generated by Django 4.1.5 on 2023-01-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.CharField(default='q', max_length=50),
            preserve_default=False,
        ),
    ]
